version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/flaskapp
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ubuntu
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: ubuntu
