# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MusicApp-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicApp-ios
    pod 'pop', '~> 1.0'
    pod 'Koloda', '~> 4.3.1'


  target 'MusicApp-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
